"""add mitre_techniques table

Revision ID: 939d22e2dd14
Revises: 153fe6bdf55b
Create Date: 2026-09-08 00:21:28.709968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '939d22e2dd14'
down_revision: Union[str, Sequence[str], None] = '153fe6bdf55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mitre_techniques',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('attack_path_id', sa.String(), nullable=False),
    sa.Column('technique_id', sa.String(), nullable=False),
    sa.Column('technique_name', sa.String(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['attack_path_id'], ['attack_paths.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mitre_techniques')
    # ### end Alembic commands ###
